was-cluster-emb:
  name: "was-cluster-emb default"
  version: "0.0"
  fileupload: .
spring:
  application:
    name: was-cluster-emb
primary:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.81.208.227:3306/demo?useUnicode=true&serverTimezone=Asia/Seoul
    user: devon
    password: devon1234
    initialization-mode: always
    sql-script-encoding: utf-8
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialec
    hikari:
      maximum-pool-size: 5
secondary:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.81.208.228:3301/demo
    user: test1
    password: test01
    initialization-mode: always
    sql-script-encoding: utf-8
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hikari:
      maximum-pool-size: 15
